[package]
name = "pmt"
version = "0.1.0"
license = "MIT"
edition = "2021"
default-run = "pmt"
rust-version = "1.81"

[dependencies]
egui = { version = "0.29.1"}
egui_extras = "0.29.1"
eframe = { version = "0.29.1" }
strum = { version = "0.26.1", features = ["derive"] }
bs58 = "0.5.0"
copypasta = "0.10.1"
dpp = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147", features = [
    "client",
] }
platform-serialization-derive = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147" }
dash-sdk = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147" }
drive = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147" }
drive-proof-verifier = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147" }
thiserror = "1"
serde = "1.0.197"
serde_json = "1.0.120"
toml = { version = "0.8.10", features = ["display"] }
dapi-grpc = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147", features = [
    "client",
] }
rs-dapi-client = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147" }
tokio = { version = "1.36.0", features = ["full"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
strategy-tests = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147" }
simple-signer = { git = "https://github.com/dashpay/platform", commit = "1d431ce3ef6d1df7f1dc4788643de156e9bdb147" }
reqwest = { version = "0.12.3", features = ["json"] }
hex = { version = "0.4.3" }
itertools = "0.13.0"
futures = "0.3.30"
walkdir = "2"
rand = "0.8"
memoize = "0.4.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
dotenvy = "0.15.7"
envy = "0.4.2"
clap = { version = "4.5.1", features = ["derive"] }
governor = "0.6.3"
tokio-util = "0.7.10"
chrono = "0.4"
chrono-humanize = "0.2.3"
dashmap = "5.5.3"
grovedb-version = "2.0.3"
sha2 = "0.10.8"
arboard = { version = "3.4.0", default-features = false, features = ["windows-sys"] }

hdrhistogram = "7.5.4"
rusqlite = { version = "0.32.1"}

