name: Release Dash Evo Tool

on:
  push:
    tags:
      - 'v*'
      - 'v*-dev.*'
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: "Version (i.e. v0.1.0)"
        required: true

jobs:
  build-and-release:
    name: Build and Release Dash Evo Tool
    strategy:
      matrix:
        arch: [amd64, arm64]  # matrix for  amd64 and arm64
        include:
          - platform: linux/amd64
            runner_tags: ["self-hosted", "Linux", "X64"]  # X64 runner tags
            target: x86_64-unknown-linux-gnu
          - platform: linux/arm64
            runner_tags: ["self-hosted", "Linux", "ARM64"]  #  ARM64 runner tags
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.runner_tags }}  # runs on  specific runner based on architecture and tags

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Install essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config clang cmake unzip libsqlite3-dev && uname -a && pwd

      - name: Install protoc
        run: curl -Lo /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v25.2/protoc-25.2-linux-aarch_64.zip && sudo unzip -f /tmp/protoc.zip -d /usr/local && rm /tmp/protoc.zip
        env:
          PROTOC: /usr/local/bin/protoc
  
      - name: Build project
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dash-evo-tool-${{ matrix.platform }}
          path: target/aarch64-unknown-linux-gnu/release/dash-evo-tool

    continue-on-error: true

  release:
    name: Create GitHub Release
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dash-evo-tool-*
          path: ./release

      - name: Publish release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./release/dash-evo-tool-*
          draft: false
          prerelease: false