name: Release Dash Evo Tool

on:
  push:
    tags:
      - 'v*'
      - 'v*-dev.*'
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: "Version (i.e. v0.1.0)"
        required: true

jobs:
  build-and-release:
    name: Build and Release Dash Evo Tool
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        include:
          - platform: linux/amd64
            os: ubuntu-latest
            arch: amd64
            target: x86_64-unknown-linux-gnu
          - platform: linux/arm64
            os: ubuntu-latest
            arch: arm64
            target: aarch64-unknown-linux-gnu
          - platform: macos/amd64
            os: macos-latest
            arch: amd64
            target: x86_64-apple-darwin
          - platform: macos/arm64
            os: macos-latest
            arch: arm64
            target: aarch64-apple-darwin
    steps:
      - uses: dtolnay/rust-toolchain@master
        name: Install Rust toolchain
        with:
          toolchain: stable

      - name: Install protoc
        id: deps-protoc
        shell: bash
        run: |
          curl -Lo /tmp/protoc.zip \
            https://github.com/protocolbuffers/protobuf/releases/download/v25.2/protoc-25.2-linux-x86_64.zip
          unzip /tmp/protoc.zip -d ${HOME}/.local
          echo "PROTOC=${HOME}/.local/bin/protoc" >> $GITHUB_ENV
          export PATH="${PATH}:${HOME}/.local/bin"

      # Install cross-compilation toolchain for ARM on Linux
      - name: Install cross-compilation toolchain (only for arm64)
        if: matrix.arch == 'arm64' && matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set environment variables for cross-compilation
        if: matrix.arch == 'arm64' && matrix.os == 'ubuntu-latest'
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++

      - name: Install pkg-config for ARM64
        if: matrix.arch == 'arm64' && matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y pkg-config-aarch64-linux-gnu

      - name: Set pkg-config environment variable for cross-compilation
        if: matrix.arch == 'arm64' && matrix.os == 'ubuntu-latest'
        run: |
          echo "PKG_CONFIG=aarch64-linux-gnu-pkg-config" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dash-evo-tool-${{ matrix.platform }}
          path: target/${{ matrix.target }}/release/dash-evo-tool

    continue-on-error: true

  release:
    name: Create GitHub Release
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dash-evo-tool-*
          path: ./release

      - name: Publish release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./release/dash-evo-tool-*
          draft: false
          prerelease: false