name: Release Dash Evo Tool

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: "Version (i.e. v1.0.0)"
        required: true

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            arch: arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            arch: amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install dependencies for cross-compilation (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dash-evo-tool-${{ matrix.os }}-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/dash-evo-tool

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dash-evo-tool-*
          path: ./release

      - name: Set up release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./release/dash-evo-tool-*
          draft: false
          prerelease: false