name: Release Dash Evo Tool

on:
  push:
    tags:
      - 'v*'
      - 'v*-dev.*'
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: "Version (e.g., v0.1.0)"
        required: true

jobs:
  build-and-release:
    name: Build and Release Dash Evo Tool
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            os: ubuntu-latest
            arch: amd64
            target: x86_64-unknown-linux-gnu
          - platform: linux/arm64
            os: ubuntu-latest
            arch: arm64
            target: aarch64-unknown-linux-gnu
          - platform: macos/amd64
            os: macos-latest
            arch: amd64
            target: x86_64-apple-darwin
          - platform: macos/arm64
            os: macos-latest
            arch: arm64
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rust-src

      - name: Install cross
        if: matrix.os == 'ubuntu-latest'
        run: cargo install cross

      # Build custom Docker image for ARM64 Linux
      - name: Build custom cross Docker image
        if: matrix.arch == 'arm64' && matrix.os == 'ubuntu-latest'
        run: |
          docker build -t my-custom-cross:aarch64 -f ./.github/workflows/Dockerfile .

      # Install protoc on macOS
      - name: Install protoc on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install protobuf

      # Build project
      - name: Build project
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi
        env:
          CROSS_CONTAINER_ENGINE: docker

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dash-evo-tool-${{ matrix.platform }}
          path: target/${{ matrix.target }}/release/dash-evo-tool

  release:
    name: Create GitHub Release
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dash-evo-tool-*
          path: ./release

      - name: Publish release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./release/dash-evo-tool-*
          draft: false
          prerelease: false
